-- =============================================
-- 관리기능 메뉴 구조 생성
-- 구조:
--   관리기능 (1depth, PORTAL_MENU_ADMIN)
--     └ 포탈 컨텐츠 관리 (2depth, PORTAL_MENU_CONTENT_MGMT)
--         └ 공지사항 (3depth, PORTAL_MENU_ADMIN_NOTICE)
-- =============================================

DECLARE @SYS_ID NVARCHAR(50);
DECLARE @WORKGROUP_ID NVARCHAR(50);
DECLARE @MENU_TYPE_CODE_ID NVARCHAR(50);

SELECT TOP 1 @SYS_ID = SYS_ID FROM TN_CF_SYS;
SELECT @WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';
SELECT TOP 1 @MENU_TYPE_CODE_ID = CODE_ID FROM TC_CF_COMM_CODE WHERE CODE_ID LIKE 'MENU_TYPE%' AND DELETE_YN = '0';

-- =============================================
-- 1. 기존 PORTAL_MENU_NOTICE_WRITE 메뉴 정리
--    (공지사항 관리 메뉴를 새 구조로 이동하므로 비활성화)
-- =============================================
UPDATE TN_CF_MENU SET USE_YN = '0' WHERE MENU_ID = 'PORTAL_MENU_NOTICE_WRITE';

-- =============================================
-- 2. SYS_RESOURCE 등록
-- =============================================

-- 관리기능 1depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_ADMIN', 'PORTAL_MENU_ROOT', @SYS_ID, '관리기능', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_ADMIN SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_ADMIN 이미 존재'

-- 포탈 컨텐츠 관리 2depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_CONTENT_MGMT')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_CONTENT_MGMT', 'PORTAL_MENU_ADMIN', @SYS_ID, '포탈 컨텐츠 관리', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_CONTENT_MGMT SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_CONTENT_MGMT 이미 존재'

-- 공지사항 3depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN_NOTICE')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_ADMIN_NOTICE', 'PORTAL_MENU_CONTENT_MGMT', @SYS_ID, '공지사항', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_ADMIN_NOTICE SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_ADMIN_NOTICE 이미 존재'

-- =============================================
-- 3. MENU 등록
-- =============================================

-- 관리기능 1depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_ADMIN')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_ADMIN', '관리기능', '{"ko":"관리기능","en":"Admin"}', 99, 1,
     '1', '0', @MENU_TYPE_CODE_ID, '0', NULL)
    PRINT 'PORTAL_MENU_ADMIN MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '관리기능', USE_YN = '1', DELETE_YN = '0', MENU_SEQUENCE = 99
    WHERE MENU_ID = 'PORTAL_MENU_ADMIN'
    PRINT 'PORTAL_MENU_ADMIN MENU 업데이트'
END

-- 포탈 컨텐츠 관리 2depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_CONTENT_MGMT')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_CONTENT_MGMT', '포탈 컨텐츠 관리', '{"ko":"포탈 컨텐츠 관리","en":"Content Mgmt"}', 1, 2,
     '1', '0', @MENU_TYPE_CODE_ID, '0', NULL)
    PRINT 'PORTAL_MENU_CONTENT_MGMT MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '포탈 컨텐츠 관리', USE_YN = '1', DELETE_YN = '0', MENU_SEQUENCE = 1
    WHERE MENU_ID = 'PORTAL_MENU_CONTENT_MGMT'
    PRINT 'PORTAL_MENU_CONTENT_MGMT MENU 업데이트'
END

-- 공지사항 3depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_ADMIN_NOTICE')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_ADMIN_NOTICE', '공지사항', '{"ko":"공지사항","en":"Notice"}', 1, 3,
     '1', '0', @MENU_TYPE_CODE_ID, '0', '/admin/notices')
    PRINT 'PORTAL_MENU_ADMIN_NOTICE MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '공지사항', USE_YN = '1', DELETE_YN = '0',
        EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = '/admin/notices', MENU_SEQUENCE = 1
    WHERE MENU_ID = 'PORTAL_MENU_ADMIN_NOTICE'
    PRINT 'PORTAL_MENU_ADMIN_NOTICE MENU 업데이트'
END

-- =============================================
-- 4. testuser 권한 부여 (3개 모두)
-- =============================================

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@WORKGROUP_ID, 'PORTAL_MENU_ADMIN', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_ADMIN 권한 등록'
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_CONTENT_MGMT')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@WORKGROUP_ID, 'PORTAL_MENU_CONTENT_MGMT', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_CONTENT_MGMT 권한 등록'
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN_NOTICE')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@WORKGROUP_ID, 'PORTAL_MENU_ADMIN_NOTICE', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_ADMIN_NOTICE 권한 등록'
END

-- =============================================
-- 5. 최종 확인
-- =============================================
SELECT M.MENU_ID, SR.UPPER_SYS_RESOURCE_ID, M.LABEL, M.MENU_LEVEL,
       M.MENU_SEQUENCE, M.USE_YN, M.EXTERNAL_URL
FROM   TN_CF_MENU M
       JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE  M.MENU_ID LIKE 'PORTAL_MENU_ADMIN%'
   OR  M.MENU_ID LIKE 'PORTAL_MENU_CONTENT%'
ORDER BY M.MENU_LEVEL, M.MENU_SEQUENCE;
