-- =============================================
-- 배너관리 메뉴 등록
-- 메뉴 경로: 관리기능 > 포탈컨텐츠관리 > 배너관리
-- admin_menu_setup.sql 패턴과 동일하게 작성
-- =============================================

DECLARE @SYS_ID NVARCHAR(50);
DECLARE @WORKGROUP_ID NVARCHAR(50);
DECLARE @MENU_TYPE_CODE_ID NVARCHAR(50);

SELECT TOP 1 @SYS_ID = SYS_ID FROM TN_CF_SYS;
SELECT @WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';
SELECT TOP 1 @MENU_TYPE_CODE_ID = CODE_ID FROM TC_CF_COMM_CODE WHERE CODE_ID LIKE 'MENU_TYPE%' AND DELETE_YN = '0';

-- =============================================
-- 1. SYS_RESOURCE 등록 (PORTAL_MENU_CONTENT_MGMT 하위)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN_BANNER')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_ADMIN_BANNER', 'PORTAL_MENU_CONTENT_MGMT', @SYS_ID, '배너관리', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT 'PORTAL_MENU_ADMIN_BANNER SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_ADMIN_BANNER 이미 존재'

-- =============================================
-- 2. MENU 등록 (3depth, PORTAL_MENU_CONTENT_MGMT 하위, 공지사항(seq=1) 다음)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_ADMIN_BANNER')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_ADMIN_BANNER', '배너관리', '{"ko":"배너관리","en":"Banner"}', 2, 3,
     '1', '0', @MENU_TYPE_CODE_ID, '0', '/admin/banners')
    PRINT 'PORTAL_MENU_ADMIN_BANNER MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '배너관리', USE_YN = '1', DELETE_YN = '0',
        EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = '/admin/banners', MENU_SEQUENCE = 2
    WHERE MENU_ID = 'PORTAL_MENU_ADMIN_BANNER'
    PRINT 'PORTAL_MENU_ADMIN_BANNER MENU 업데이트'
END

-- =============================================
-- 3. testuser 권한 부여
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_ADMIN_BANNER')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@WORKGROUP_ID, 'PORTAL_MENU_ADMIN_BANNER', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_ADMIN_BANNER 권한 등록'
END
ELSE PRINT 'PORTAL_MENU_ADMIN_BANNER 권한 이미 존재'

-- =============================================
-- 4. 확인 쿼리
-- =============================================
SELECT M.MENU_ID, SR.UPPER_SYS_RESOURCE_ID, M.LABEL, M.MENU_LEVEL,
       M.MENU_SEQUENCE, M.USE_YN, M.EXTERNAL_URL
FROM   TN_CF_MENU M
       JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE  M.MENU_ID LIKE 'PORTAL_MENU_ADMIN%'
   OR  M.MENU_ID LIKE 'PORTAL_MENU_CONTENT%'
ORDER BY M.MENU_LEVEL, M.MENU_SEQUENCE;
