-- ============================================================
-- 공통코드 데이터 이관 SQL
-- 구 DB: MOPORTAL_DEV (TC_CF_COMM_CODE_TYPE, TC_CF_COMM_CODE)
-- 신 DB: SDL_DEV      (TC_CF_COMM_CODE_TYPE, TC_CF_COMM_CODE)
-- 작성일: 2026-06-05
-- ============================================================
-- [컬럼 차이 요약]
-- 구 DB: KO_LABEL(한국어), EN_LABEL(영어), LABEL(=EN_LABEL), DELETE_YN(nvarchar)
-- 신 DB: LABEL(=EN_LABEL), LABEL_JSON({"ko_KR":"...", "en_US":"..."}), DELETE_YN(bit)
-- 구 DB: COMM_CODE_TYPE_NAME이 NULL → KO_LABEL로 대체
-- ============================================================

-- STEP 0: 이관 전 건수 확인 (신 DB에서 실행)
/*
SELECT 'TC_CF_COMM_CODE_TYPE' AS 테이블명, COUNT(*) AS 건수 FROM TC_CF_COMM_CODE_TYPE
UNION ALL
SELECT 'TC_CF_COMM_CODE',                  COUNT(*) FROM TC_CF_COMM_CODE;
*/

BEGIN TRANSACTION;

-- 1단계: TC_CF_COMM_CODE_TYPE (부모 테이블)
-- 변환: COMM_CODE_TYPE_NAME(NULL) → ISNULL(KO_LABEL, CODE), KO_LABEL+EN_LABEL → LABEL_JSON, DELETE_YN(nvarchar→bit)
INSERT INTO TC_CF_COMM_CODE_TYPE (
    COMM_CODE_TYPE_CODE, COMM_CODE_TYPE_NAME, DESCRIPTION,
    FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID,
    LABEL, LABEL_JSON, DELETE_YN, FROM_DATE, THRU_DATE
)
SELECT
    COMM_CODE_TYPE_CODE,
    ISNULL(KO_LABEL, COMM_CODE_TYPE_CODE),
    DESCRIPTION,
    FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID,
    ISNULL(EN_LABEL, ''),
    '{"ko_KR":"' + ISNULL(REPLACE(KO_LABEL, '"', ''), '') + '",'
    + '"en_US":"' + ISNULL(REPLACE(EN_LABEL, '"', ''), '') + '"}',
    CAST(ISNULL(DELETE_YN, '0') AS bit),
    FROM_DATE, THRU_DATE
FROM [MOPORTAL_DEV].[dbo].TC_CF_COMM_CODE_TYPE S
WHERE NOT EXISTS (
    SELECT 1 FROM TC_CF_COMM_CODE_TYPE
     WHERE COMM_CODE_TYPE_CODE = S.COMM_CODE_TYPE_CODE
);

-- 2단계: TC_CF_COMM_CODE (자식 테이블)
-- 변환: LABEL → EN_LABEL(표시명), KO_LABEL+EN_LABEL → LABEL_JSON, DELETE_YN(nvarchar→bit)
INSERT INTO TC_CF_COMM_CODE (
    CODE_ID, CODE, UPPER_CODE_ID, DESCRIPTION,
    COMM_CODE_TYPE_CODE, HIERARCHY_LEVEL, ORD,
    FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID,
    LABEL, LABEL_JSON, DELETE_YN, FROM_DATE, THRU_DATE
)
SELECT
    CODE_ID, CODE, UPPER_CODE_ID, DESCRIPTION,
    COMM_CODE_TYPE_CODE, HIERARCHY_LEVEL, ORD,
    FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID,
    ISNULL(EN_LABEL, ''),
    '{"ko_KR":"' + ISNULL(REPLACE(KO_LABEL, '"', ''), '') + '",'
    + '"en_US":"' + ISNULL(REPLACE(EN_LABEL, '"', ''), '') + '"}',
    CAST(ISNULL(DELETE_YN, '0') AS bit),
    FROM_DATE, THRU_DATE
FROM [MOPORTAL_DEV].[dbo].TC_CF_COMM_CODE S
WHERE NOT EXISTS (
    SELECT 1 FROM TC_CF_COMM_CODE
     WHERE CODE_ID = S.CODE_ID
);

COMMIT;

-- STEP 후: 이관 후 건수 확인 (신 DB에서 실행)
/*
SELECT 'TC_CF_COMM_CODE_TYPE' AS 테이블명, COUNT(*) AS 건수 FROM TC_CF_COMM_CODE_TYPE
UNION ALL
SELECT 'TC_CF_COMM_CODE',                  COUNT(*) FROM TC_CF_COMM_CODE;
*/
