-- =============================================
-- DS Mobile 공지사항 데이터 이관
-- 구 DB(MOPORTAL_DEV) → 신 DB(SDL_DEV)
-- 대상: TN_CF_DSMOBILE_NOTICE, TN_CF_DSMOBILE_NOTICE_APP
-- =============================================

-- STEP 0: 구 DB 컬럼 확인 쿼리 (참고용)
/*
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('TN_CF_DSMOBILE_NOTICE', 'TN_CF_DSMOBILE_NOTICE_APP')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT TOP 3 * FROM TN_CF_DSMOBILE_NOTICE ORDER BY REG_DATE DESC;
SELECT TOP 3 * FROM TN_CF_DSMOBILE_NOTICE_APP;
*/

-- =============================================
-- STEP 1: DDL — 신규 DB에 테이블 생성
-- (두 테이블 모두 신규 DB에 없음 — 구 소스 컬럼 구조 그대로 생성)
-- =============================================

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TN_CF_DSMOBILE_NOTICE')
BEGIN
    CREATE TABLE TN_CF_DSMOBILE_NOTICE (
        UID         VARCHAR(50)   NOT NULL,
        TITLE       VARCHAR(200)  NOT NULL,
        MESSAGE     VARCHAR(2000) NOT NULL,
        START_DATE  DATETIME      NULL,
        END_DATE    DATETIME      NULL,
        USED        VARCHAR(1)    NULL,
        REG_DATE    DATETIME      NULL  DEFAULT GETDATE(),
        MOD_DATE    DATETIME      NULL,
        CATEGORY    VARCHAR(50)   NULL,
        FILE_ID     VARCHAR(50)   NULL,
        EMPLY_TYPE  VARCHAR(1)    NULL,
        IS_ACTIVE   VARCHAR(1)    NULL,
        CONSTRAINT PK_TN_CF_DSMOBILE_NOTICE PRIMARY KEY (UID)
    );
    PRINT 'TN_CF_DSMOBILE_NOTICE 테이블 생성 완료';
END
ELSE PRINT 'TN_CF_DSMOBILE_NOTICE 이미 존재';

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TN_CF_DSMOBILE_NOTICE_APP')
BEGIN
    -- 구 iBatis XML 기준: APP_ID, TARGET_UID 두 컬럼 (TARGET_UID → TN_CF_DSMOBILE_NOTICE.UID FK)
    CREATE TABLE TN_CF_DSMOBILE_NOTICE_APP (
        APP_ID      VARCHAR(100)  NOT NULL,
        TARGET_UID  VARCHAR(50)   NOT NULL,
        CONSTRAINT PK_TN_CF_DSMOBILE_NOTICE_APP PRIMARY KEY (APP_ID, TARGET_UID),
        CONSTRAINT FK_DSMOBILE_NOTICE_APP_UID
            FOREIGN KEY (TARGET_UID) REFERENCES TN_CF_DSMOBILE_NOTICE(UID)
    );
    PRINT 'TN_CF_DSMOBILE_NOTICE_APP 테이블 생성 완료';
END
ELSE PRINT 'TN_CF_DSMOBILE_NOTICE_APP 이미 존재';

-- =============================================
-- STEP 2: 데이터 이관
-- =============================================

BEGIN TRANSACTION;

-- 2-1: TN_CF_DSMOBILE_NOTICE 이관 (부모 테이블 먼저)
INSERT INTO TN_CF_DSMOBILE_NOTICE (
    UID, TITLE, MESSAGE, START_DATE, END_DATE,
    USED, REG_DATE, MOD_DATE, CATEGORY, FILE_ID, EMPLY_TYPE, IS_ACTIVE
)
SELECT
    UID, TITLE, MESSAGE, START_DATE, END_DATE,
    USED, REG_DATE, MOD_DATE, CATEGORY, FILE_ID, EMPLY_TYPE, IS_ACTIVE
FROM [MOPORTAL_DEV].[dbo].TN_CF_DSMOBILE_NOTICE S
WHERE NOT EXISTS (
    SELECT 1 FROM TN_CF_DSMOBILE_NOTICE WHERE UID = S.UID
);
PRINT 'TN_CF_DSMOBILE_NOTICE 이관: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- 2-2: TN_CF_DSMOBILE_NOTICE_APP 이관 (자식 테이블)
INSERT INTO TN_CF_DSMOBILE_NOTICE_APP (APP_ID, TARGET_UID)
SELECT APP_ID, TARGET_UID
FROM [MOPORTAL_DEV].[dbo].TN_CF_DSMOBILE_NOTICE_APP S
WHERE NOT EXISTS (
    SELECT 1 FROM TN_CF_DSMOBILE_NOTICE_APP
    WHERE APP_ID = S.APP_ID AND TARGET_UID = S.TARGET_UID
);
PRINT 'TN_CF_DSMOBILE_NOTICE_APP 이관: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

COMMIT;

-- =============================================
-- STEP 3: 확인
-- =============================================
SELECT COUNT(*) AS notice_count FROM TN_CF_DSMOBILE_NOTICE;
SELECT COUNT(*) AS notice_app_count FROM TN_CF_DSMOBILE_NOTICE_APP;
SELECT TOP 3 UID, TITLE, START_DATE, END_DATE, USED, EMPLY_TYPE, IS_ACTIVE
FROM TN_CF_DSMOBILE_NOTICE ORDER BY REG_DATE DESC;
