-- ============================================================
-- 설비보안점검 (ESC) 데이터 이관
-- 구 DB: MOPORTAL_DEV → 신 DB: SDL_DEV
-- 마이그레이션 단계: 26단계 (5_5), 27단계 (5_6)
-- 전제: esc_ddl.sql 실행 완료 후 이 파일 실행
-- FK 체인 순서: GBM_LINE → EQUIPMENT → EQP_MAP → EQP_MAP_ATTACH/FILE
--               → EQP_SAVE_LIST → EQP_SCHEDULE → SCHEDULE_LIST
--               → SCHEDULE_HISTORY → FAB_ETC_DEVICE_CHECK
-- ============================================================

BEGIN TRANSACTION;

-- ============================================================
-- STEP 1: ESC_DATA_GBM_LINE (부모 테이블 — FK 없음)
-- 주의: 구 DB 자체에 PK 중복 레코드 존재 → ROW_NUMBER로 중복 제거
-- ============================================================
INSERT INTO ESC_DATA_GBM_LINE (GBM_CODE, LINE_CODE, LINE_NM, LINE_ABBR_NM)
SELECT GBM_CODE, LINE_CODE, LINE_NM, LINE_ABBR_NM
FROM (
    SELECT GBM_CODE, LINE_CODE, LINE_NM, LINE_ABBR_NM,
           ROW_NUMBER() OVER (PARTITION BY GBM_CODE, LINE_CODE ORDER BY LINE_NM) AS RN
    FROM MOPORTAL_DEV.dbo.ESC_DATA_GBM_LINE
) S
WHERE S.RN = 1
  AND NOT EXISTS (
    SELECT 1 FROM ESC_DATA_GBM_LINE T
    WHERE T.GBM_CODE = S.GBM_CODE AND T.LINE_CODE = S.LINE_CODE
);
PRINT 'ESC_DATA_GBM_LINE 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 2: ESC_DATA_EQUIPMENT (부모 테이블 — FK 없음)
-- ============================================================
INSERT INTO ESC_DATA_EQUIPMENT (
    EQP_IDG_CODE, EQP_NM, EQP_ID, EQP_REG_KND_CODE_DESC_KO,
    AREA_CLS_CODE, EQP_L1_CLASS_CODE, EQP_L1_CLASS_CODE_DESC_KO,
    EQP_L2_CLASS_CODE, EQP_L2_CLASS_CODE_DESC_KO,
    LARGE_PROCESS_CLASS_CODE, LARGE_PROCESS_CLASS_CODE_NM_KO,
    MIDD_PROCESS_CLASS_CODE, MIDD_PROCESS_CLASS_CODE_NM_KO,
    SMALL_PROCESS_CLASS_CODE, SMALL_PROCESS_CLASS_CODE_NM_KO,
    MAIN_EQP_KND_CODE, MAIN_EQP_KND_CODE_DESC_KO,
    EQP_STATUS_CODE, EQP_STATUS_CODE_DESC_KO,
    EQP_SETUP_START_DATE, WAFER_SIZE_CODE, WAFER_SIZE_CODE_DESC_KO,
    MAKER_NM, MAKER_COMPANY_NM, MODEL_NM, MAKER_SRL_NO,
    AMS_MASTER_CODE, ASET_NO, ASET_STATUS_CODE, ASET_STATUS_CODE_DESC_KO,
    GBM_CODE, EQP_SDWT_INTRNL_ID, SDWT_ID, SDWT_NM,
    OWN_ORG_REF_ID, OWN_ORG_NM,
    LFCL_MANAGE_ORG_REF_ID, LFCL_MANAGE_ORG_CODE, LFCL_MANAGE_ORG_NM, LFCL_MGR_EMPNO,
    IDX_LINE_DISTN_CODE, IDX_LINE_DISTN_CODE_DESC_KO,
    EQP_LOC_INFO, SITE_CODE, DSTRT_CODE, FLOOR_CODE, BAY_CODE, SETUP_RESPEN_EMPNO,
    CSYS_LINE_DISTN_CODE, CSYS_LINE_DISTN_CODE_DESC_KO,
    CSYS_LINE_DISTN_CODE_DESC_EN, CSYS_LINE_DISTN_CODE_DESC_CN, CSYS_LINE_CODE,
    OWN_LINE_DISTN_CODE, OWN_LINE_DISTN_CODE_DESC_KO,
    OWN_LINE_DISTN_CODE_DESC_EN, OWN_LINE_DISTN_CODE_DESC_CN, OWN_LINE_CODE,
    IF_DATE, IF_EMP
)
SELECT
    EQP_IDG_CODE, EQP_NM, EQP_ID, EQP_REG_KND_CODE_DESC_KO,
    AREA_CLS_CODE, EQP_L1_CLASS_CODE, EQP_L1_CLASS_CODE_DESC_KO,
    EQP_L2_CLASS_CODE, EQP_L2_CLASS_CODE_DESC_KO,
    LARGE_PROCESS_CLASS_CODE, LARGE_PROCESS_CLASS_CODE_NM_KO,
    MIDD_PROCESS_CLASS_CODE, MIDD_PROCESS_CLASS_CODE_NM_KO,
    SMALL_PROCESS_CLASS_CODE, SMALL_PROCESS_CLASS_CODE_NM_KO,
    MAIN_EQP_KND_CODE, MAIN_EQP_KND_CODE_DESC_KO,
    EQP_STATUS_CODE, EQP_STATUS_CODE_DESC_KO,
    EQP_SETUP_START_DATE, WAFER_SIZE_CODE, WAFER_SIZE_CODE_DESC_KO,
    MAKER_NM, MAKER_COMPANY_NM, MODEL_NM, MAKER_SRL_NO,
    AMS_MASTER_CODE, ASET_NO, ASET_STATUS_CODE, ASET_STATUS_CODE_DESC_KO,
    GBM_CODE, EQP_SDWT_INTRNL_ID, SDWT_ID, SDWT_NM,
    OWN_ORG_REF_ID, OWN_ORG_NM,
    LFCL_MANAGE_ORG_REF_ID, LFCL_MANAGE_ORG_CODE, LFCL_MANAGE_ORG_NM, LFCL_MGR_EMPNO,
    IDX_LINE_DISTN_CODE, IDX_LINE_DISTN_CODE_DESC_KO,
    EQP_LOC_INFO, SITE_CODE, DSTRT_CODE, FLOOR_CODE, BAY_CODE, SETUP_RESPEN_EMPNO,
    CSYS_LINE_DISTN_CODE, CSYS_LINE_DISTN_CODE_DESC_KO,
    CSYS_LINE_DISTN_CODE_DESC_EN, CSYS_LINE_DISTN_CODE_DESC_CN, CSYS_LINE_CODE,
    OWN_LINE_DISTN_CODE, OWN_LINE_DISTN_CODE_DESC_KO,
    OWN_LINE_DISTN_CODE_DESC_EN, OWN_LINE_DISTN_CODE_DESC_CN, OWN_LINE_CODE,
    IF_DATE, IF_EMP
FROM MOPORTAL_DEV.dbo.ESC_DATA_EQUIPMENT
WHERE NOT EXISTS (
    SELECT 1 FROM ESC_DATA_EQUIPMENT T WHERE T.EQP_IDG_CODE = MOPORTAL_DEV.dbo.ESC_DATA_EQUIPMENT.EQP_IDG_CODE
);
PRINT 'ESC_DATA_EQUIPMENT 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 3: ESC_EQP_MAP (설비맵 메타정보)
-- ============================================================
INSERT INTO ESC_EQP_MAP (EQP_MAP_ID, EQP_AREA, EQP_LINE, EQP_PROCESS, EQP_MODEL,
                         REG_DATE, REG_USER, DELETE_YN, MOD_DATE, MOD_USER)
SELECT EQP_MAP_ID, EQP_AREA, EQP_LINE, EQP_PROCESS, EQP_MODEL,
       REG_DATE, REG_USER, DELETE_YN, MOD_DATE, MOD_USER
FROM MOPORTAL_DEV.dbo.ESC_EQP_MAP
WHERE NOT EXISTS (
    SELECT 1 FROM ESC_EQP_MAP T WHERE T.EQP_MAP_ID = MOPORTAL_DEV.dbo.ESC_EQP_MAP.EQP_MAP_ID
);
PRINT 'ESC_EQP_MAP 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 4: ESC_EQP_MAP_ATTACH (설비맵 첨부파일 — ESC_EQP_MAP 하위)
-- 주의: 구 DB에 부모(ESC_EQP_MAP) 없는 고아 레코드 존재 → EXISTS로 부모 확인
-- ============================================================
INSERT INTO ESC_EQP_MAP_ATTACH (FILE_ID, EQP_MAP_ID, FILE_PATH, FILE_NAME,
                                FILE_SIZE, ORIGINAL_NAME, REG_DATE, REG_USER)
SELECT SRC.FILE_ID, SRC.EQP_MAP_ID, SRC.FILE_PATH, SRC.FILE_NAME,
       SRC.FILE_SIZE, SRC.ORIGINAL_NAME, SRC.REG_DATE, SRC.REG_USER
FROM MOPORTAL_DEV.dbo.ESC_EQP_MAP_ATTACH SRC
WHERE EXISTS (
    SELECT 1 FROM ESC_EQP_MAP P WHERE P.EQP_MAP_ID = SRC.EQP_MAP_ID
)
  AND NOT EXISTS (
    SELECT 1 FROM ESC_EQP_MAP_ATTACH T WHERE T.FILE_ID = SRC.FILE_ID
);
PRINT 'ESC_EQP_MAP_ATTACH 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 5: ESC_EQP_MAP_FILE (설비별 이미지 파일)
-- ============================================================
INSERT INTO ESC_EQP_MAP_FILE (FILE_ID, EQP_IDG_CODE, FILE_PATH, FILE_NAME,
                              FILE_SIZE, ORIGINAL_NAME, REG_DATE, REG_USER)
SELECT FILE_ID, EQP_IDG_CODE, FILE_PATH, FILE_NAME,
       FILE_SIZE, ORIGINAL_NAME, REG_DATE, REG_USER
FROM MOPORTAL_DEV.dbo.ESC_EQP_MAP_FILE
WHERE NOT EXISTS (
    SELECT 1 FROM ESC_EQP_MAP_FILE T WHERE T.FILE_ID = MOPORTAL_DEV.dbo.ESC_EQP_MAP_FILE.FILE_ID
);
PRINT 'ESC_EQP_MAP_FILE 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 6: ESC_EQP_SAVE_LIST (사용자별 GBM/LINE 설정값)
-- 주의: 구 DB 자체에 PK 중복 레코드 존재 → ROW_NUMBER로 중복 제거
-- ============================================================
INSERT INTO ESC_EQP_SAVE_LIST (REG_USER, GBM_CODE, LINE_CODE)
SELECT REG_USER, GBM_CODE, LINE_CODE
FROM (
    SELECT REG_USER, GBM_CODE, LINE_CODE,
           ROW_NUMBER() OVER (PARTITION BY REG_USER, GBM_CODE, LINE_CODE ORDER BY REG_USER) AS RN
    FROM MOPORTAL_DEV.dbo.ESC_EQP_SAVE_LIST
) S
WHERE S.RN = 1
  AND NOT EXISTS (
    SELECT 1 FROM ESC_EQP_SAVE_LIST T
    WHERE T.REG_USER  = S.REG_USER
      AND T.GBM_CODE  = S.GBM_CODE
      AND T.LINE_CODE = S.LINE_CODE
);
PRINT 'ESC_EQP_SAVE_LIST 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 7: ESC_EQP_SCHEDULE (점검 스케줄 마스터)
-- ============================================================
INSERT INTO ESC_EQP_SCHEDULE (SCH_ID, TITLE, START_DATE, END_DATE, REG_DATE, REG_USER, USE_YN)
SELECT SCH_ID, TITLE, START_DATE, END_DATE, REG_DATE, REG_USER, USE_YN
FROM MOPORTAL_DEV.dbo.ESC_EQP_SCHEDULE
WHERE NOT EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE T WHERE T.SCH_ID = MOPORTAL_DEV.dbo.ESC_EQP_SCHEDULE.SCH_ID
);
PRINT 'ESC_EQP_SCHEDULE 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 8: ESC_EQP_SCHEDULE_LIST (_DROP_ 컬럼 제외)
-- 주의: 구 DB 자체에 PK 중복 레코드 존재 + 고아 레코드 존재
--       → ROW_NUMBER로 중복 제거, EXISTS로 부모(SCHEDULE) 확인
-- ============================================================
INSERT INTO ESC_EQP_SCHEDULE_LIST (
    SCH_ID, GBM_CODE, LINE_CODE, EQP_ID, STATUS,
    REG_USER_ID, REG_DATE, UPDATE_USER_ID, UPDATE_DATE,
    USB_PORT_CNT, USB_BLOCK_CNT, USB_BLOCK_OFF_CNT, USB_BLOCK_OFF_REASON,
    ETC_DEVICE, REMOTE_APPLIED, VACCINE_APPLIED, VACCINE_NAME,
    SCREEN_SAVER_APPLIED, SCREEN_SAVER_NAME, LOCATION, REMOTE_NAME, EQP_IDG_CODE
)
SELECT
    SCH_ID, GBM_CODE, LINE_CODE, EQP_ID, STATUS,
    REG_USER_ID, REG_DATE, UPDATE_USER_ID, UPDATE_DATE,
    USB_PORT_CNT, USB_BLOCK_CNT, USB_BLOCK_OFF_CNT, USB_BLOCK_OFF_REASON,
    ETC_DEVICE, REMOTE_APPLIED, VACCINE_APPLIED, VACCINE_NAME,
    SCREEN_SAVER_APPLIED, SCREEN_SAVER_NAME, LOCATION, REMOTE_NAME, EQP_IDG_CODE
FROM (
    SELECT SCH_ID, GBM_CODE, LINE_CODE, EQP_ID, STATUS,
           REG_USER_ID, REG_DATE, UPDATE_USER_ID, UPDATE_DATE,
           USB_PORT_CNT, USB_BLOCK_CNT, USB_BLOCK_OFF_CNT, USB_BLOCK_OFF_REASON,
           ETC_DEVICE, REMOTE_APPLIED, VACCINE_APPLIED, VACCINE_NAME,
           SCREEN_SAVER_APPLIED, SCREEN_SAVER_NAME, LOCATION, REMOTE_NAME, EQP_IDG_CODE,
           ROW_NUMBER() OVER (PARTITION BY SCH_ID, GBM_CODE, LINE_CODE, EQP_ID ORDER BY UPDATE_DATE DESC) AS RN
    FROM MOPORTAL_DEV.dbo.ESC_EQP_SCHEDULE_LIST
) S
WHERE S.RN = 1
  AND EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE P WHERE P.SCH_ID = S.SCH_ID
)
  AND NOT EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE_LIST T
    WHERE T.SCH_ID    = S.SCH_ID
      AND T.GBM_CODE  = S.GBM_CODE
      AND T.LINE_CODE = S.LINE_CODE
      AND T.EQP_ID    = S.EQP_ID
);
PRINT 'ESC_EQP_SCHEDULE_LIST 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 9: ESC_EQP_SCHEDULE_HISTORY
-- 주의: 구 DB에 부모(ESC_EQP_SCHEDULE) 없는 고아 레코드 존재 → EXISTS로 부모 확인
-- ============================================================
INSERT INTO ESC_EQP_SCHEDULE_HISTORY (SCH_ID, EQP_IDG_CODE, EQP_ID, UPDATE_DATE)
SELECT SRC.SCH_ID, SRC.EQP_IDG_CODE, SRC.EQP_ID, SRC.UPDATE_DATE
FROM MOPORTAL_DEV.dbo.ESC_EQP_SCHEDULE_HISTORY SRC
WHERE EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE P WHERE P.SCH_ID = SRC.SCH_ID
)
  AND NOT EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE_HISTORY T
    WHERE T.SCH_ID       = SRC.SCH_ID
      AND T.EQP_ID       = SRC.EQP_ID
      AND ISNULL(T.UPDATE_DATE,'1900-01-01') = ISNULL(SRC.UPDATE_DATE,'1900-01-01')
);
PRINT 'ESC_EQP_SCHEDULE_HISTORY 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- ============================================================
-- STEP 10: ESC_FAB_ETC_DEVICE_CHECK
-- 주의: 구 DB 자체에 PK 중복 레코드 존재 + 고아 레코드 존재
--       → ROW_NUMBER로 중복 제거, EXISTS로 부모(SCHEDULE) 확인
-- ============================================================
INSERT INTO ESC_FAB_ETC_DEVICE_CHECK (
    SCH_ID, EQP_ID, ETC_DEVICE_NAME, BLOCK_APPLIED,
    BLOCK_OFF_REASON, BLOCK_OFF_DETAIL_REASON, EQP_IDG_CODE
)
SELECT SCH_ID, EQP_ID, ETC_DEVICE_NAME, BLOCK_APPLIED,
       BLOCK_OFF_REASON, BLOCK_OFF_DETAIL_REASON, EQP_IDG_CODE
FROM (
    SELECT SCH_ID, EQP_ID, ETC_DEVICE_NAME, BLOCK_APPLIED,
           BLOCK_OFF_REASON, BLOCK_OFF_DETAIL_REASON, EQP_IDG_CODE,
           ROW_NUMBER() OVER (PARTITION BY SCH_ID, EQP_ID, ETC_DEVICE_NAME ORDER BY SCH_ID) AS RN
    FROM MOPORTAL_DEV.dbo.ESC_FAB_ETC_DEVICE_CHECK
) S
WHERE S.RN = 1
  AND EXISTS (
    SELECT 1 FROM ESC_EQP_SCHEDULE P WHERE P.SCH_ID = S.SCH_ID
)
  AND NOT EXISTS (
    SELECT 1 FROM ESC_FAB_ETC_DEVICE_CHECK T
    WHERE T.SCH_ID          = S.SCH_ID
      AND T.EQP_ID          = S.EQP_ID
      AND T.ETC_DEVICE_NAME = S.ETC_DEVICE_NAME
);
PRINT 'ESC_FAB_ETC_DEVICE_CHECK 이관 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

COMMIT;

-- ============================================================
-- 확인 쿼리
-- ============================================================
SELECT 'ESC_DATA_GBM_LINE'        AS 테이블, COUNT(*) AS 건수 FROM ESC_DATA_GBM_LINE
UNION ALL SELECT 'ESC_DATA_EQUIPMENT',      COUNT(*) FROM ESC_DATA_EQUIPMENT
UNION ALL SELECT 'ESC_EQP_MAP',             COUNT(*) FROM ESC_EQP_MAP
UNION ALL SELECT 'ESC_EQP_MAP_ATTACH',      COUNT(*) FROM ESC_EQP_MAP_ATTACH
UNION ALL SELECT 'ESC_EQP_MAP_FILE',        COUNT(*) FROM ESC_EQP_MAP_FILE
UNION ALL SELECT 'ESC_EQP_SAVE_LIST',       COUNT(*) FROM ESC_EQP_SAVE_LIST
UNION ALL SELECT 'ESC_EQP_SCHEDULE',        COUNT(*) FROM ESC_EQP_SCHEDULE
UNION ALL SELECT 'ESC_EQP_SCHEDULE_LIST',   COUNT(*) FROM ESC_EQP_SCHEDULE_LIST
UNION ALL SELECT 'ESC_EQP_SCHEDULE_HISTORY',COUNT(*) FROM ESC_EQP_SCHEDULE_HISTORY
UNION ALL SELECT 'ESC_FAB_ETC_DEVICE_CHECK',COUNT(*) FROM ESC_FAB_ETC_DEVICE_CHECK;
