-- ============================================================
-- 설비보안점검 메뉴 등록 (기준정보등록 + 설비MAP 이미지 등록 + 점검대상등록)
-- 마이그레이션 단계: 26단계 (5_5), 27단계 (5_6)
-- ============================================================

/* STEP 0 — 구 DB 메뉴 조회 (참고용)
SELECT M.MENU_ID, M.LABEL, M.LABEL_JSON, M.MENU_LEVEL, M.MENU_SEQUENCE, M.EXTERNAL_URL,
       SR.UPPER_SYS_RESOURCE_ID AS 부모ID
FROM TN_CF_MENU M
JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE SR.UPPER_SYS_RESOURCE_ID = 'AWswncmcABIe-jTl'
ORDER BY M.MENU_SEQUENCE;

-- 결과:
-- AWswnlMMABMe-jTl  기준정보등록           seq=0  부모=AWswncmcABIe-jTl
-- AWswn1ecABQe-jTl  설비MAP 이미지 등록    seq=1  부모=AWswncmcABIe-jTl
-- AWswtdJMABUe-jTl  점검대상등록           seq=2  부모=AWswncmcABIe-jTl
*/

DECLARE @PARENT_ID      NVARCHAR(50) = 'AWswncmcABIe-jTl';  -- 설비보안점검 그룹
DECLARE @MENU_MAP       NVARCHAR(50) = 'AWswn1ecABQe-jTl';  -- 설비MAP 이미지 등록
DECLARE @MENU_SCHEDULE  NVARCHAR(50) = 'AWswtdJMABUe-jTl';  -- 점검대상등록
DECLARE @MENU_BASIC     NVARCHAR(50) = 'AWswnlMMABMe-jTl';  -- 기준정보등록
DECLARE @URL_MAP        NVARCHAR(200) = '/portal/upload/security/map';
DECLARE @URL_SCHEDULE   NVARCHAR(200) = '/portal/upload/security/inspection';
DECLARE @URL_BASIC      NVARCHAR(200) = '/portal/upload/security/basic';
DECLARE @WORKGROUP_ID   NVARCHAR(50);

SELECT @WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';

-- ============================================================
-- STEP 1: 설비MAP 이미지 등록 메뉴
-- ============================================================
IF EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = @MENU_MAP)
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '설비MAP 이미지 등록',
        LABEL_JSON = '{"ko_KR":"설비MAP 이미지 등록","en_US":"Equipment Map Image"}',
        MENU_SEQUENCE = 1, MENU_LEVEL = 4, USE_YN = '1', DELETE_YN = '0',
        MENU_TYPE_CODE_ID = 'ATMQ58N6AABlL532', MENU_USE_PERIOD_CODE = 'A',
        EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = @URL_MAP
    WHERE MENU_ID = @MENU_MAP;
    PRINT 'TN_CF_MENU UPDATE (MAP) 완료';
END
ELSE
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, MENU_USE_PERIOD_CODE,
     EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    (@MENU_MAP, '설비MAP 이미지 등록',
     '{"ko_KR":"설비MAP 이미지 등록","en_US":"Equipment Map Image"}',
     1, 4, '1', '0', 'ATMQ58N6AABlL532', 'A', '0', @URL_MAP);
    PRINT 'TN_CF_MENU INSERT (MAP) 완료';
END

IF EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = @MENU_MAP)
BEGIN
    UPDATE TN_CF_SYS_RESOURCE
    SET UPPER_SYS_RESOURCE_ID = @PARENT_ID, LAST_MOD_DATETIME = GETDATE(), LAST_MODR_ID = 'admin'
    WHERE SYS_RESOURCE_ID = @MENU_MAP;
END
ELSE
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@MENU_MAP, @PARENT_ID, GETDATE(), 'admin', GETDATE(), 'admin');
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE WORKGROUP_ID = @WORKGROUP_ID AND SYS_RESOURCE_ID = @MENU_MAP AND USER_ID = 'testuser')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@WORKGROUP_ID, @MENU_MAP, 'READ', 'testuser',
            CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT 'testuser 권한 등록 (MAP) 완료';
END

-- ============================================================
-- STEP 2: 점검대상등록 메뉴
-- ============================================================
IF EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = @MENU_SCHEDULE)
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '점검대상등록',
        LABEL_JSON = '{"ko_KR":"점검대상등록","en_US":"Inspection Target"}',
        MENU_SEQUENCE = 2, MENU_LEVEL = 4, USE_YN = '1', DELETE_YN = '0',
        MENU_TYPE_CODE_ID = 'ATMQ58N6AABlL532', MENU_USE_PERIOD_CODE = 'A',
        EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = @URL_SCHEDULE
    WHERE MENU_ID = @MENU_SCHEDULE;
    PRINT 'TN_CF_MENU UPDATE (SCHEDULE) 완료';
END
ELSE
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, MENU_USE_PERIOD_CODE,
     EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    (@MENU_SCHEDULE, '점검대상등록',
     '{"ko_KR":"점검대상등록","en_US":"Inspection Target"}',
     2, 4, '1', '0', 'ATMQ58N6AABlL532', 'A', '0', @URL_SCHEDULE);
    PRINT 'TN_CF_MENU INSERT (SCHEDULE) 완료';
END

IF EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = @MENU_SCHEDULE)
BEGIN
    UPDATE TN_CF_SYS_RESOURCE
    SET UPPER_SYS_RESOURCE_ID = @PARENT_ID, LAST_MOD_DATETIME = GETDATE(), LAST_MODR_ID = 'admin'
    WHERE SYS_RESOURCE_ID = @MENU_SCHEDULE;
END
ELSE
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@MENU_SCHEDULE, @PARENT_ID, GETDATE(), 'admin', GETDATE(), 'admin');
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE WORKGROUP_ID = @WORKGROUP_ID AND SYS_RESOURCE_ID = @MENU_SCHEDULE AND USER_ID = 'testuser')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@WORKGROUP_ID, @MENU_SCHEDULE, 'READ', 'testuser',
            CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT 'testuser 권한 등록 (SCHEDULE) 완료';
END

-- ============================================================
-- STEP 3: 기준정보등록 메뉴
-- ============================================================
IF EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = @MENU_BASIC)
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '기준정보등록',
        LABEL_JSON = '{"ko_KR":"기준정보등록","en_US":"Basic Info Registration"}',
        MENU_SEQUENCE = 0, MENU_LEVEL = 4, USE_YN = '1', DELETE_YN = '0',
        MENU_TYPE_CODE_ID = 'ATMQ58N6AABlL532', MENU_USE_PERIOD_CODE = 'A',
        EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = @URL_BASIC
    WHERE MENU_ID = @MENU_BASIC;
    PRINT 'TN_CF_MENU UPDATE (BASIC) 완료';
END
ELSE
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, MENU_USE_PERIOD_CODE,
     EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    (@MENU_BASIC, '기준정보등록',
     '{"ko_KR":"기준정보등록","en_US":"Basic Info Registration"}',
     0, 4, '1', '0', 'ATMQ58N6AABlL532', 'A', '0', @URL_BASIC);
    PRINT 'TN_CF_MENU INSERT (BASIC) 완료';
END

IF EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = @MENU_BASIC)
BEGIN
    UPDATE TN_CF_SYS_RESOURCE
    SET UPPER_SYS_RESOURCE_ID = @PARENT_ID, LAST_MOD_DATETIME = GETDATE(), LAST_MODR_ID = 'admin'
    WHERE SYS_RESOURCE_ID = @MENU_BASIC;
END
ELSE
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@MENU_BASIC, @PARENT_ID, GETDATE(), 'admin', GETDATE(), 'admin');
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE WORKGROUP_ID = @WORKGROUP_ID AND SYS_RESOURCE_ID = @MENU_BASIC AND USER_ID = 'testuser')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES (@WORKGROUP_ID, @MENU_BASIC, 'READ', 'testuser',
            CONVERT(VARCHAR(8), GETDATE(), 112), '99991231', GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT 'testuser 권한 등록 (BASIC) 완료';
END

-- ============================================================
-- 확인 쿼리
-- ============================================================
SELECT M.MENU_ID, M.LABEL, M.MENU_LEVEL, M.MENU_SEQUENCE, M.EXTERNAL_URL,
       SR.UPPER_SYS_RESOURCE_ID AS 부모ID
FROM TN_CF_MENU M
JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE SR.UPPER_SYS_RESOURCE_ID = 'AWswncmcABIe-jTl'
ORDER BY M.MENU_SEQUENCE;
