-- =============================================
-- FAQ 데이터 이관: 구 DB TN_CF_SDPCOMMU (BBS_ID='moFAQ') → 신 DB TN_CF_POST (BOARD_ID='faq')
-- 구 DB 건수: 28건
-- FK: TN_CF_POST.BOARD_ID → TN_CF_BOARD.BOARD_ID (신 DB에 'faq' 보드 존재 확인 완료)
-- =============================================

-- 사전 확인: 신 DB TN_CF_BOARD faq 존재 여부
-- SELECT BOARD_ID FROM TN_CF_BOARD WHERE BOARD_ID = 'faq';

BEGIN TRANSACTION;

INSERT INTO TN_CF_POST (
    POST_ID,
    BOARD_ID,
    POST_TITLE,
    POST_DETAIL,
    UPPER_POST_ID,
    HIERARCHY_LEVEL,
    REPLY_SEQUENCE,
    USE_YN,
    EMP_TYPE,
    NOTICE_POPUP_YN,
    NOTICE_POPUP_START_DATE,
    NOTICE_POPUP_END_DATE,
    NOTICE_POPUP_WIDTH,
    NOTICE_POPUP_HEIGHT,
    NOTICE_LABEL_YN,
    NOTICE_LABEL_TYPE,
    NOTICE_LABEL_START_DATE,
    NOTICE_LABEL_END_DATE,
    DELETE_YN,
    FIRST_REGR_ID,
    FIRST_REG_DATETIME,
    LAST_MODR_ID,
    LAST_MOD_DATETIME
)
SELECT
    S.COMMU_ID,
    'faq',
    S.COMMU_TITLE,
    S.COMMU_DETAIL,
    NULL,
    ISNULL(S.HIERARCHY_LEVEL, 1),
    ISNULL(S.REPLY_PRIORITY, 0),
    -- DELETE_YN='N' → USE_YN='Y', 그 외 → 'N'
    CASE WHEN S.DELETE_YN = 'N' THEN 'Y' ELSE 'N' END,
    NULL,   -- EMP_TYPE 없음
    -- POPUP_YN='Y' → '1', 'N' → '0'
    CASE WHEN S.POPUP_YN = 'Y' THEN '1' ELSE '0' END,
    NULL,
    NULL,
    ISNULL(S.POPUP_WIDTH_LENGTH, 500),
    ISNULL(S.POPUP_VERTICAL_LENGTH, 400),
    '0',
    NULL,
    NULL,
    NULL,
    '0',
    S.FIRST_REGR_ID,
    S.FIRST_REG_DATETIME,
    S.LAST_MODR_ID,
    S.LAST_MOD_DATETIME
FROM [MOPORTAL_DEV].[dbo].[TN_CF_SDPCOMMU] S
WHERE S.BBS_ID = 'moFAQ'
  AND NOT EXISTS (
      SELECT 1 FROM TN_CF_POST P WHERE P.POST_ID = S.COMMU_ID
  );

PRINT CAST(@@ROWCOUNT AS NVARCHAR) + '건 이관 완료';

COMMIT;

-- 이관 결과 확인
SELECT COUNT(*) AS FAQ_COUNT FROM TN_CF_POST WHERE BOARD_ID = 'faq';
