-- =============================================
-- FAQ 분류 등록 + CLASSIFICATION_ID 매핑
-- 구 DB TN_CF_SDPBBS_CLSFTN (BBS_ID='moFAQ') 5개 분류
-- =============================================

-- =============================================
-- STEP 1. TN_CF_BOARD CLASSIFICATION_USE_YN 활성화
-- =============================================
UPDATE TN_CF_BOARD
SET    CLASSIFICATION_USE_YN = '1',
       LAST_MOD_DATETIME     = GETDATE(),
       LAST_MODR_ID          = 'admin'
WHERE  BOARD_ID = 'faq';
PRINT 'TN_CF_BOARD faq CLASSIFICATION_USE_YN 활성화: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- =============================================
-- STEP 2. TN_CF_BOARD_CLASSIFICATION 분류 등록 (구 DB CLASSIFICATION_ID 그대로)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_BOARD_CLASSIFICATION WHERE BOARD_ID = 'faq' AND CLASSIFICATION_ID = 'AVdQW4-sAAB_illV')
BEGIN
    INSERT INTO TN_CF_BOARD_CLASSIFICATION (BOARD_ID, CLASSIFICATION_ID, CLASSIFICATION_NAME, DESCRIPTION, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES ('faq', 'AVdQW4-sAAB_illV', 'S.Camera', NULL, GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT '분류 [S.Camera] 등록 완료';
END
ELSE PRINT '분류 [S.Camera] 이미 존재';

IF NOT EXISTS (SELECT 1 FROM TN_CF_BOARD_CLASSIFICATION WHERE BOARD_ID = 'faq' AND CLASSIFICATION_ID = 'AVdQW4-8AAF_illV')
BEGIN
    INSERT INTO TN_CF_BOARD_CLASSIFICATION (BOARD_ID, CLASSIFICATION_ID, CLASSIFICATION_NAME, DESCRIPTION, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES ('faq', 'AVdQW4-8AAF_illV', '포탈이용', NULL, GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT '분류 [포탈이용] 등록 완료';
END
ELSE PRINT '분류 [포탈이용] 이미 존재';

IF NOT EXISTS (SELECT 1 FROM TN_CF_BOARD_CLASSIFICATION WHERE BOARD_ID = 'faq' AND CLASSIFICATION_ID = 'AVdQW4-8AAJ_illV')
BEGIN
    INSERT INTO TN_CF_BOARD_CLASSIFICATION (BOARD_ID, CLASSIFICATION_ID, CLASSIFICATION_NAME, DESCRIPTION, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES ('faq', 'AVdQW4-8AAJ_illV', '권한신청', NULL, GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT '분류 [권한신청] 등록 완료';
END
ELSE PRINT '분류 [권한신청] 이미 존재';

IF NOT EXISTS (SELECT 1 FROM TN_CF_BOARD_CLASSIFICATION WHERE BOARD_ID = 'faq' AND CLASSIFICATION_ID = 'AVdQW4-8AAN_illV')
BEGIN
    INSERT INTO TN_CF_BOARD_CLASSIFICATION (BOARD_ID, CLASSIFICATION_ID, CLASSIFICATION_NAME, DESCRIPTION, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES ('faq', 'AVdQW4-8AAN_illV', 'ACS', NULL, GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT '분류 [ACS] 등록 완료';
END
ELSE PRINT '분류 [ACS] 이미 존재';

IF NOT EXISTS (SELECT 1 FROM TN_CF_BOARD_CLASSIFICATION WHERE BOARD_ID = 'faq' AND CLASSIFICATION_ID = 'AZtnsq9MAAB_rCqm')
BEGIN
    INSERT INTO TN_CF_BOARD_CLASSIFICATION (BOARD_ID, CLASSIFICATION_ID, CLASSIFICATION_NAME, DESCRIPTION, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES ('faq', 'AZtnsq9MAAB_rCqm', '기타', NULL, GETDATE(), 'admin', GETDATE(), 'admin');
    PRINT '분류 [기타] 등록 완료';
END
ELSE PRINT '분류 [기타] 이미 존재';

-- =============================================
-- STEP 3. 기존 이관된 FAQ 게시글에 CLASSIFICATION_ID 매핑
-- =============================================
UPDATE P
SET    P.CLASSIFICATION_ID = CL.BBS_CLSFTN_SERIAL_NO
FROM   TN_CF_POST P
JOIN   [MOPORTAL_DEV].[dbo].[TN_CF_SDPCOMMU_CLSFTN] CL ON P.POST_ID = CL.COMMU_ID
WHERE  P.BOARD_ID = 'faq'
  AND  P.CLASSIFICATION_ID IS NULL;
PRINT '분류 매핑 완료: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- 확인
SELECT C.CLASSIFICATION_NAME, COUNT(*) AS 건수
FROM   TN_CF_POST P
JOIN   TN_CF_BOARD_CLASSIFICATION C ON P.CLASSIFICATION_ID = C.CLASSIFICATION_ID AND C.BOARD_ID = 'faq'
WHERE  P.BOARD_ID = 'faq'
GROUP BY C.CLASSIFICATION_NAME
ORDER BY C.CLASSIFICATION_NAME;
