-- =============================================
-- GNB 메뉴 정리
-- - FAQ, 앱 관리 비활성화
-- - 앱스토어(seq=2), DS Camera(seq=3), 앱운영(seq=4) 추가
-- 최종 GNB: My Page(0) > 공지사항(1) > 앱스토어(2) > DS Camera(3) > 앱운영(4) > 사용자관리(10) > 관리기능(99)
-- =============================================

DECLARE @SYS_ID NVARCHAR(50);
DECLARE @WORKGROUP_ID NVARCHAR(50);
DECLARE @MENU_TYPE_CODE_ID NVARCHAR(50);

SELECT TOP 1 @SYS_ID = SYS_ID FROM TN_CF_SYS;
SELECT @WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';
SELECT TOP 1 @MENU_TYPE_CODE_ID = CODE_ID FROM TC_CF_COMM_CODE WHERE CODE_ID LIKE 'MENU_TYPE%' AND DELETE_YN = '0';

-- =============================================
-- 1. FAQ, 앱 관리 비활성화
-- =============================================
UPDATE TN_CF_MENU SET USE_YN = '0' WHERE MENU_ID IN ('PORTAL_MENU_FAQ', 'PORTAL_MENU_APP');
PRINT 'FAQ, 앱 관리 비활성화: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- =============================================
-- 2. 앱스토어 (seq=2)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_APP_STORE')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_APP_STORE', 'PORTAL_MENU_ROOT', @SYS_ID, '앱스토어', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_APP_STORE SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_APP_STORE SYS_RESOURCE 이미 존재'

IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_APP_STORE')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_APP_STORE', '앱스토어', '{"ko":"앱스토어","en":"App Store"}', 2, 1,
     '1', '0', @MENU_TYPE_CODE_ID, '0', NULL)
    PRINT 'PORTAL_MENU_APP_STORE MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '앱스토어', USE_YN = '1', DELETE_YN = '0', MENU_SEQUENCE = 2
    WHERE MENU_ID = 'PORTAL_MENU_APP_STORE'
    PRINT 'PORTAL_MENU_APP_STORE MENU 업데이트'
END

-- =============================================
-- 3. DS Camera (seq=3)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_DS_CAMERA')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_DS_CAMERA', 'PORTAL_MENU_ROOT', @SYS_ID, 'DS Camera', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_DS_CAMERA SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_DS_CAMERA SYS_RESOURCE 이미 존재'

IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_DS_CAMERA')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_DS_CAMERA', 'DS Camera', '{"ko":"DS Camera","en":"DS Camera"}', 3, 1,
     '1', '0', @MENU_TYPE_CODE_ID, '0', NULL)
    PRINT 'PORTAL_MENU_DS_CAMERA MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = 'DS Camera', USE_YN = '1', DELETE_YN = '0', MENU_SEQUENCE = 3
    WHERE MENU_ID = 'PORTAL_MENU_DS_CAMERA'
    PRINT 'PORTAL_MENU_DS_CAMERA MENU 업데이트'
END

-- =============================================
-- 4. 앱운영 (seq=4)
-- =============================================
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_APP_OPS')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_APP_OPS', 'PORTAL_MENU_ROOT', @SYS_ID, '앱운영', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_APP_OPS SYS_RESOURCE 등록'
END
ELSE PRINT 'PORTAL_MENU_APP_OPS SYS_RESOURCE 이미 존재'

IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_APP_OPS')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_APP_OPS', '앱운영', '{"ko":"앱운영","en":"App Ops"}', 4, 1,
     '1', '0', @MENU_TYPE_CODE_ID, '0', NULL)
    PRINT 'PORTAL_MENU_APP_OPS MENU 등록'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET LABEL = '앱운영', USE_YN = '1', DELETE_YN = '0', MENU_SEQUENCE = 4
    WHERE MENU_ID = 'PORTAL_MENU_APP_OPS'
    PRINT 'PORTAL_MENU_APP_OPS MENU 업데이트'
END

-- =============================================
-- 5. testuser 권한 일괄 부여
-- =============================================
INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID,
     FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
SELECT
    @WORKGROUP_ID, M.MENU_ID, 'READ', 'testuser',
    CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
    GETDATE(), 'admin', GETDATE(), 'admin'
FROM TN_CF_MENU M
WHERE M.MENU_ID IN ('PORTAL_MENU_APP_STORE', 'PORTAL_MENU_DS_CAMERA', 'PORTAL_MENU_APP_OPS')
  AND NOT EXISTS (
      SELECT 1 FROM TN_CF_USER_AUTHORIZATION UA
      WHERE UA.USER_ID = 'testuser' AND UA.SYS_RESOURCE_ID = M.MENU_ID
  );
PRINT 'testuser 권한 추가: ' + CAST(@@ROWCOUNT AS VARCHAR) + '건';

-- =============================================
-- 6. 확인
-- =============================================
SELECT M.MENU_ID, M.LABEL, M.MENU_LEVEL, M.MENU_SEQUENCE, M.USE_YN
FROM   TN_CF_MENU M
WHERE  M.MENU_ID LIKE 'PORTAL_MENU_%'
  AND  M.MENU_LEVEL = 1
  AND  M.DELETE_YN = '0'
ORDER BY M.MENU_SEQUENCE;
