-- ============================================================
-- My App (DS Mobile) 메뉴 URL 업데이트 + testuser 권한 등록
-- MENU_ID : AZSLR9daAADjznmQ
-- 부모 ID : AUH8d6ocABM0TZdR  (MY PAGE)
-- 신규 URL: /portal/mypage/myapp
-- ============================================================

/*
  STEP 0 — 구 DB 메뉴 조회 (참고)
  SELECT M.MENU_ID, M.LABEL, M.LABEL_JSON, M.MENU_LEVEL, M.MENU_SEQUENCE,
         SR.UPPER_SYS_RESOURCE_ID AS 부모ID
  FROM TN_CF_MENU M
  JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
  WHERE M.LABEL LIKE '%My App%'
  ORDER BY M.MENU_LEVEL, M.MENU_SEQUENCE;
  -- 결과: AZSLR9daAADjznmQ / My App (DS Mobile) / level 2 / seq 5 / 부모 AUH8d6ocABM0TZdR
*/

-- STEP 1: EXTERNAL_URL 업데이트
UPDATE TN_CF_MENU
SET EXTERNAL_URL          = '/portal/mypage/myapp',
    EXTERNAL_URL_USE_YN   = '0',
    USE_YN                = '1',
    DELETE_YN             = '0'
WHERE MENU_ID = 'AZSLR9daAADjznmQ';

-- STEP 2: testuser 권한 등록
DECLARE @WORKGROUP_ID NVARCHAR(50);
SELECT @WORKGROUP_ID = WORKGROUP_ID
FROM TN_CF_WORKGROUP
WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';

INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID,
     FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
SELECT
    @WORKGROUP_ID, 'AZSLR9daAADjznmQ', 'READ', 'testuser',
    CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
    GETDATE(), 'admin', GETDATE(), 'admin'
WHERE NOT EXISTS (
    SELECT 1 FROM TN_CF_USER_AUTHORIZATION
    WHERE SYS_RESOURCE_ID = 'AZSLR9daAADjznmQ'
      AND USER_ID = 'testuser'
);

-- 결과 확인
SELECT M.MENU_ID, M.LABEL, M.EXTERNAL_URL, M.USE_YN
FROM TN_CF_MENU M
WHERE M.MENU_ID = 'AZSLR9daAADjznmQ';

SELECT SYS_RESOURCE_ID, USER_ID, AUTHORIZATION_ID, FROM_DATE
FROM TN_CF_USER_AUTHORIZATION
WHERE SYS_RESOURCE_ID = 'AZSLR9daAADjznmQ';
