-- =============================================
-- 공지사항 메뉴 중복 제거 및 정리
-- 문제: PORTAL_MENU_NOTICE_MGMT가 기존 PORTAL_MENU_NOTICE와 중복
-- 처리: PORTAL_MENU_NOTICE_MGMT 제거, 기존 PORTAL_MENU_NOTICE 구조 유지 및 URL 정리
-- =============================================

-- 1. 새로 추가한 중복 메뉴 제거
DELETE FROM TN_CF_USER_AUTHORIZATION WHERE SYS_RESOURCE_ID IN ('PORTAL_MENU_NOTICE_MGMT', 'PORTAL_MENU_NOTICE_LIST') AND USER_ID = 'testuser';

-- SYS_RESOURCE에서도 제거 (단, PORTAL_MENU_NOTICE_LIST는 기존 것이므로 UPPER가 NOTICE_MGMT인 것만 제거)
DELETE FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_NOTICE_MGMT';

DELETE FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_NOTICE_MGMT';

-- 2. 기존 PORTAL_MENU_NOTICE (1depth) URL 정리 — 하위 메뉴가 있으므로 자체 URL은 비워둠
UPDATE TN_CF_MENU
SET    USE_YN = '1',
       DELETE_YN = '0',
       EXTERNAL_URL_USE_YN = '0',
       EXTERNAL_URL = NULL
WHERE  MENU_ID = 'PORTAL_MENU_NOTICE';

-- 3. PORTAL_MENU_NOTICE_LIST (2depth, 포털 공지사항 목록) URL 확인 및 정리
UPDATE TN_CF_MENU
SET    USE_YN = '1',
       DELETE_YN = '0',
       EXTERNAL_URL_USE_YN = '0',
       EXTERNAL_URL = '/portal/notices'
WHERE  MENU_ID = 'PORTAL_MENU_NOTICE_LIST';

-- 4. PORTAL_MENU_NOTICE_WRITE → 관리자 공지사항 등록 페이지로 연결
UPDATE TN_CF_MENU
SET    LABEL = '공지사항 관리',
       EXTERNAL_URL_USE_YN = '0',
       EXTERNAL_URL = '/admin/notices',
       USE_YN = '1',
       DELETE_YN = '0'
WHERE  MENU_ID = 'PORTAL_MENU_NOTICE_WRITE';

UPDATE TN_CF_SYS_RESOURCE
SET    SYS_RESOURCE_NAME = '공지사항 관리'
WHERE  SYS_RESOURCE_ID = 'PORTAL_MENU_NOTICE_WRITE';

-- 5. testuser에게 기존 PORTAL_MENU_NOTICE 계열 권한 확인 및 추가
DECLARE @USER_AUTH_MENU_WORKGROUP_ID NVARCHAR(50);
SELECT @USER_AUTH_MENU_WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_NOTICE')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@USER_AUTH_MENU_WORKGROUP_ID, 'PORTAL_MENU_NOTICE', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
     GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_NOTICE 권한 추가'
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_NOTICE_LIST')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@USER_AUTH_MENU_WORKGROUP_ID, 'PORTAL_MENU_NOTICE_LIST', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
     GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_NOTICE_LIST 권한 추가'
END

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_NOTICE_WRITE')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID, FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@USER_AUTH_MENU_WORKGROUP_ID, 'PORTAL_MENU_NOTICE_WRITE', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
     GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_NOTICE_WRITE 권한 추가'
END

-- 6. 최종 확인
SELECT M.MENU_ID, SR.UPPER_SYS_RESOURCE_ID, M.LABEL, M.MENU_LEVEL,
       M.MENU_SEQUENCE, M.USE_YN, M.EXTERNAL_URL
FROM   TN_CF_MENU M
       JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE  M.MENU_ID LIKE 'PORTAL_MENU_NOTICE%'
ORDER BY M.MENU_LEVEL, M.MENU_SEQUENCE;
