-- ============================================================
-- TN_CF_USER 데이터 이관 SQL
-- 구 DB: MOPORTAL_DEV.TN_CF_USER → 신 DB: SDL_DEV.TN_CF_USER
-- 작성일: 2026-06-05
-- ============================================================
-- [컬럼 차이 요약]
-- 구 DB USER_NAME: NULL (암호화) → USER_ID로 대체
-- 구 DB SINGLE_ID → 신 DB KNOX_ID
-- ACTIVE_FLAG / EXTERNAL_USER_FLAG / PRIVACY_POLICY / DELETED: numeric → bit
-- 신 DB 전용: KNOX_ID(←SINGLE_ID), EU_GDPR_POLICY, LOGIN_ERROR_COUNT, TIME_ZONE_ID,
--             LAST_PW_CHANGE_DATETIME, SERVER_LOCATION, JWT, LAST_ACTIVITY_TIME → 기본값
-- ============================================================

-- STEP 0: 이관 전 건수 확인
/*
SELECT COUNT(*) AS 구DB건수 FROM [MOPORTAL_DEV].[dbo].TN_CF_USER;
SELECT COUNT(*) AS 신DB건수 FROM TN_CF_USER;
*/

BEGIN TRANSACTION;

INSERT INTO TN_CF_USER (
    USER_ID, PASSWORD, ACTIVE_FLAG, EXTERNAL_USER_FLAG,
    SYS_ID, EMP_NO,
    RECENT_LOGIN_IP, RECENT_LOGIN_DATETIME,
    FIRST_REG_DATETIME, FIRST_REGR_ID,
    LAST_MOD_DATETIME, LAST_MODR_ID,
    KNOX_ID,
    FIRST_NAME, LAST_NAME, DISPLAY_NAME,
    USER_NAME,
    COMP_NAME, COMP_CODE,
    DEPT_NAME, DEPT_CODE,
    GRD_NAME, GRD_CODE,
    NICK_NAME,
    EN_USER_NAME, EN_FIRST_NAME, EN_LAST_NAME,
    EN_COMP_NAME, EN_DEPT_NAME, EN_GRD_NAME,
    COMP_TEL_NO, MOBILE_TEL_NO, EMAIL_ADDRESS,
    LANGUAGE_CODE, TIME_ZONE_CODE,
    LAST_LOGIN_DATETIME, LAST_LOGIN_IP, LAST_LOGOUT_DATETIME,
    EXPIRE_STATUS_CODE, DESCRIPTION, USER_TYPE,
    PRIVACY_POLICY, PRIVACY_POLICY_DATE,
    DELETED,
    -- 신 DB 전용 컬럼 기본값
    EU_GDPR_POLICY, EU_GDPR_POLICY_DATE,
    LOGIN_ERROR_COUNT,
    TIME_ZONE_ID, LAST_PW_CHANGE_DATETIME,
    SERVER_LOCATION, JWT, LAST_ACTIVITY_TIME
)
SELECT
    USER_ID,
    PASSWORD,
    CAST(ACTIVE_FLAG AS bit),
    CAST(EXTERNAL_USER_FLAG AS bit),
    SYS_ID,
    EMP_NO,
    RECENT_LOGIN_IP, RECENT_LOGIN_DATETIME,
    FIRST_REG_DATETIME, FIRST_REGR_ID,
    LAST_MOD_DATETIME, LAST_MODR_ID,
    SINGLE_ID,                              -- SINGLE_ID → KNOX_ID
    FIRST_NAME, LAST_NAME, DISPLAY_NAME,
    ISNULL(USER_NAME, USER_ID),             -- USER_NAME NULL → USER_ID로 대체
    COMP_NAME, COMP_CODE,
    DEPT_NAME, DEPT_CODE,
    GRD_NAME, GRD_CODE,
    NICK_NAME,
    EN_USER_NAME, EN_FIRST_NAME, EN_LAST_NAME,
    EN_COMP_NAME, EN_DEPT_NAME, EN_GRD_NAME,
    LEFT(COMP_TEL_NO, 35), MOBILE_TEL_NO, EMAIL_ADDRESS,  -- COMP_TEL_NO: 구 100 → 신 35, 잘림 방지
    LANGUAGE_CODE, TIME_ZONE_CODE,
    LAST_LOGIN_DATETIME, LAST_LOGIN_IP, LAST_LOGOUT_DATETIME,
    EXPIRE_STATUS_CODE, DESCRIPTION, USER_TYPE,
    CAST(PRIVACY_POLICY AS bit), PRIVACY_POLICY_DATE,
    CAST(DELETED AS bit),
    -- 신 DB 전용 기본값
    0,      -- EU_GDPR_POLICY
    NULL,   -- EU_GDPR_POLICY_DATE
    0,      -- LOGIN_ERROR_COUNT
    NULL,   -- TIME_ZONE_ID
    NULL,   -- LAST_PW_CHANGE_DATETIME
    NULL,   -- SERVER_LOCATION
    NULL,   -- JWT
    NULL    -- LAST_ACTIVITY_TIME
FROM [MOPORTAL_DEV].[dbo].TN_CF_USER S
WHERE NOT EXISTS (
    SELECT 1 FROM TN_CF_USER
     WHERE USER_ID = S.USER_ID
);

COMMIT;

-- STEP 후: 이관 후 건수 확인
/*
SELECT COUNT(*) AS 신DB건수 FROM TN_CF_USER;
*/
