-- =============================================
-- 사용자 관리 메뉴 등록 (SDL 표준 스키마)
-- 대상 테이블: TN_CF_SYS_RESOURCE, TN_CF_MENU, TN_CF_USER_AUTHORIZATION
-- 목적: 포털 GNB 사용자 관리 메뉴 진입점 추가
-- 작성일: 2026-05-19
-- =============================================

-- =============================================
-- 사전 확인: 아래 쿼리로 값 확인 후 진행
-- =============================================
-- SELECT * FROM TN_CF_SYS;
-- SELECT WORKGROUP_ID, WORKGROUP_NAME FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';
-- SELECT CODE_ID, CODE FROM TC_CF_COMM_CODE WHERE CODE_ID LIKE 'MENU_TYPE%';

DECLARE @SYS_ID NVARCHAR(50);
DECLARE @USER_AUTH_MENU_WORKGROUP_ID NVARCHAR(50);
DECLARE @MENU_TYPE_CODE_ID NVARCHAR(50);

SELECT TOP 1 @SYS_ID = SYS_ID FROM TN_CF_SYS;
SELECT @USER_AUTH_MENU_WORKGROUP_ID = WORKGROUP_ID FROM TN_CF_WORKGROUP WHERE WORKGROUP_NAME = 'USER_AUTH_MENU';
SELECT TOP 1 @MENU_TYPE_CODE_ID = CODE_ID FROM TC_CF_COMM_CODE WHERE CODE_ID LIKE 'MENU_TYPE%' AND DELETE_YN = '0';

PRINT '사용할 SYS_ID: ' + ISNULL(@SYS_ID, 'NULL');
PRINT '사용할 WORKGROUP_ID: ' + ISNULL(@USER_AUTH_MENU_WORKGROUP_ID, 'NULL');

IF @SYS_ID IS NULL
BEGIN
    RAISERROR('SYS_ID를 찾을 수 없습니다.', 16, 1); RETURN;
END
IF @USER_AUTH_MENU_WORKGROUP_ID IS NULL
BEGIN
    RAISERROR('USER_AUTH_MENU 워크그룹을 찾을 수 없습니다.', 16, 1); RETURN;
END

-- =============================================
-- 1. TN_CF_SYS_RESOURCE 등록
-- 구 소스: TSMP_MENU (MENU_ID=PORTAL_USER_MGMT)
-- =============================================

-- 사용자 관리 1depth 메뉴 리소스
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_USER_MGMT')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_USER_MGMT', 'PORTAL_MENU_ROOT', @SYS_ID, '사용자 관리 메뉴', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_USER_MGMT SYS_RESOURCE 등록 완료'
END
ELSE
    PRINT 'PORTAL_MENU_USER_MGMT SYS_RESOURCE 이미 존재'

-- 사용자 목록 2depth 메뉴 리소스
IF NOT EXISTS (SELECT 1 FROM TN_CF_SYS_RESOURCE WHERE SYS_RESOURCE_ID = 'PORTAL_MENU_USER_LIST')
BEGIN
    INSERT INTO TN_CF_SYS_RESOURCE
    (SYS_RESOURCE_ID, UPPER_SYS_RESOURCE_ID, SYS_ID, SYS_RESOURCE_NAME, SYS_RESOURCE_TYPE_CODE_ID,
     DELETE_YN, FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    ('PORTAL_MENU_USER_LIST', 'PORTAL_MENU_USER_MGMT', @SYS_ID, '사용자 목록', 'MENU',
     '0', GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'PORTAL_MENU_USER_LIST SYS_RESOURCE 등록 완료'
END
ELSE
    PRINT 'PORTAL_MENU_USER_LIST SYS_RESOURCE 이미 존재'

-- =============================================
-- 2. TN_CF_MENU 등록
-- 변경: 구 소스 URL /portal/user/listPortalUsers.do → /portal/users (Vue 라우트 경로)
-- EXTERNAL_URL_USE_YN='0' + EXTERNAL_URL에 내부 라우트 경로 저장 → navigateMenu에서 router.push()로 처리
-- =============================================

-- 사용자 관리 1depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_USER_MGMT')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_USER_MGMT', '사용자관리', '{"ko":"사용자관리","en":"User Management"}', 10, 1,
     '1', '0', @MENU_TYPE_CODE_ID, '0', '/portal/users')
    PRINT 'PORTAL_MENU_USER_MGMT MENU 등록 완료'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET    LABEL = '사용자관리',
           LABEL_JSON = '{"ko":"사용자관리","en":"User Management"}',
           MENU_SEQUENCE = 10, MENU_LEVEL = 1, USE_YN = '1',
           EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = '/portal/users'
    WHERE  MENU_ID = 'PORTAL_MENU_USER_MGMT'
    PRINT 'PORTAL_MENU_USER_MGMT MENU 업데이트 완료'
END

-- 사용자 목록 2depth
IF NOT EXISTS (SELECT 1 FROM TN_CF_MENU WHERE MENU_ID = 'PORTAL_MENU_USER_LIST')
BEGIN
    INSERT INTO TN_CF_MENU
    (MENU_ID, LABEL, LABEL_JSON, MENU_SEQUENCE, MENU_LEVEL,
     USE_YN, DELETE_YN, MENU_TYPE_CODE_ID, EXTERNAL_URL_USE_YN, EXTERNAL_URL)
    VALUES
    ('PORTAL_MENU_USER_LIST', '사용자 목록', '{"ko":"사용자 목록","en":"User List"}', 1, 2,
     '1', '0', @MENU_TYPE_CODE_ID, '0', '/portal/users')
    PRINT 'PORTAL_MENU_USER_LIST MENU 등록 완료'
END
ELSE
BEGIN
    UPDATE TN_CF_MENU
    SET    LABEL = '사용자 목록',
           LABEL_JSON = '{"ko":"사용자 목록","en":"User List"}',
           MENU_SEQUENCE = 1, MENU_LEVEL = 2, USE_YN = '1',
           EXTERNAL_URL_USE_YN = '0', EXTERNAL_URL = '/portal/users'
    WHERE  MENU_ID = 'PORTAL_MENU_USER_LIST'
    PRINT 'PORTAL_MENU_USER_LIST MENU 업데이트 완료'
END

-- =============================================
-- 3. TN_CF_USER_AUTHORIZATION: testuser 권한 부여
-- =============================================

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION
               WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_USER_MGMT')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID,
     FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@USER_AUTH_MENU_WORKGROUP_ID, 'PORTAL_MENU_USER_MGMT', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
     GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'testuser - PORTAL_MENU_USER_MGMT 권한 등록 완료'
END
ELSE
    PRINT 'testuser - PORTAL_MENU_USER_MGMT 권한 이미 존재'

IF NOT EXISTS (SELECT 1 FROM TN_CF_USER_AUTHORIZATION
               WHERE USER_ID = 'testuser' AND SYS_RESOURCE_ID = 'PORTAL_MENU_USER_LIST')
BEGIN
    INSERT INTO TN_CF_USER_AUTHORIZATION
    (WORKGROUP_ID, SYS_RESOURCE_ID, AUTHORIZATION_ID, USER_ID,
     FROM_DATE, THRU_DATE,
     FIRST_REG_DATETIME, FIRST_REGR_ID, LAST_MOD_DATETIME, LAST_MODR_ID)
    VALUES
    (@USER_AUTH_MENU_WORKGROUP_ID, 'PORTAL_MENU_USER_LIST', 'READ', 'testuser',
     CONVERT(VARCHAR(8), GETDATE(), 112), '99991231',
     GETDATE(), 'admin', GETDATE(), 'admin')
    PRINT 'testuser - PORTAL_MENU_USER_LIST 권한 등록 완료'
END
ELSE
    PRINT 'testuser - PORTAL_MENU_USER_LIST 권한 이미 존재'

-- =============================================
-- 4. 최종 확인 쿼리
-- =============================================
SELECT M.MENU_ID, SR.UPPER_SYS_RESOURCE_ID, M.LABEL, M.MENU_LEVEL,
       M.MENU_SEQUENCE, M.USE_YN, M.EXTERNAL_URL_USE_YN, M.EXTERNAL_URL
FROM   TN_CF_MENU M
       JOIN TN_CF_SYS_RESOURCE SR ON M.MENU_ID = SR.SYS_RESOURCE_ID
WHERE  M.MENU_ID LIKE 'PORTAL_MENU_USER%'
ORDER BY M.MENU_LEVEL, M.MENU_SEQUENCE;

SELECT UA.USER_ID, UA.SYS_RESOURCE_ID, UA.AUTHORIZATION_ID
FROM   TN_CF_USER_AUTHORIZATION UA
WHERE  UA.USER_ID = 'testuser'
AND    UA.SYS_RESOURCE_ID LIKE 'PORTAL_MENU_USER%';
